on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

concurrency:
  group: '测试'
  cancel-in-progress: true

jobs:
  build-wasm:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup system
      run: |
        pacman -Syyu --noconfirm docker docker-buildx wget git base-devel

        mkdir -p c2w
        wget https://github.com/container2wasm/container2wasm/releases/download/v0.8.2/container2wasm-v0.8.2-linux-amd64.tar.gz -O c2w/container2wasm-v0.8.2-linux-amd64.tar.gz
        tar -zxvf c2w/container2wasm-v0.8.2-linux-amd64.tar.gz
        mv c2w/c2w /usr/local/bin/c2w
        mv c2w/c2w-net /usr/local/bin/c2w-net

        mkdir -p target

    - name: Build wasm
      run: |
        c2w --dockerfile ./Dockerfile alpine:3.20 target/out.wasm

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: out
        path: target/*
        retention-days: 5
